# Python versions for matrix
language: python
python:
  - "2.7"
  - "2.6"


# Django versions for matrix
env:
  - DJANGO_VERSION=1.4.15
  - DJANGO_VERSION=1.4.18
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.3

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors --quiet
  - pip install django-bootstrap3

# Command to run tests, e.g. python setup.py test
script:
- python manage.py test

# Support Python3 only with Django 1.6+
# Support Django 1.7+ only with Python 2.7+
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.3
